# Source: rabbitmq/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
     app.kubernetes.io/name: rabbitmq
     helm.sh/chart: rabbitmq-11.13.0
     app.kubernetes.io/instance: rabbitmq
     app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  rabbitmq-password: "MDhvRmlkczd3alhnVHk5aQ=="
  
  rabbitmq-erlang-cookie: "RkpGZkN4S3hEM2p4bEIxMGV3WDVMb01tVHNwSmZBQ0k="
