apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # echo -n "cookie-value" | base64
  RABBITMQ_ERLANG_COOKIE: V0lXVkhDRFRDSVVBV0FOTE1RQVc=
