apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.rabbitmq.labels.name.app }}
spec:
  clusterIP: None
  ports:
  - port: 4369
    targetPort: 4369
    name: discovery
  - port: 5672
    targetPort: 5672
    name: amqp
  selector:
    app: {{ .Values.rabbitmq.labels.name.app }}
