namespace: rabbits

rabbitmq:
    deployment:
        name: rabbitmq
        image: rabbitmq:3.8-management
        replicaCount: 4
    service:
        name: rabbitmq
        #type: NodePort
        port: 8080
        targetport: 8080
    labels:
        name: 
           app: rabbitmq
    container:
        name: rabbitmq
    serviceAccountName: rabbitmq
    storageClassName: standard
    secret:
        name: rabbit-secret
    configmap:
        name: rabbitmq-config
    ingress:
         host: rabbitmq.example.com

